### PR TITLE
Update googleads/google-ads-php to latest version in LaravelSampleApp

### LINKED ISSUE #447: Updating dependencies for LaravelSampleApp example
**Which version of the client library are you using?**
v5

**Which version of PHP are you using?**
7.4.3

**Which operating system (Linux, Windows, ...) and version?**
Ubuntu 20.04.1 LTS

**Actions taken**
I am trying to run the LaravelSampleApp example but I am getting the error `Class Google\Ads\GoogleAds\Lib\V5\GoogleAdsClient does not exist`, because composer installed the 3 version of the library by default

**Expected result**
version 5 is installed by default

**Actual result**
screenshot with error

### PR DESCRIPTION
**Pull request by Neverage**
Fixes #447

### CODE REVIEW

**Comment by Neverage** [comment]
@googlebot I signed it!

**Comment by Neverage** [comment]
@googlebot I consent

**Review by PierrickVoulet — APPROVED** [review]
This looks good to me, thank you for the contribution!

**Comment by Neverage** [comment]
@PierrickVoulet, thank you!

I'm sorry, do i need commit with correct author(name, email) using a force push for the googlebot to approve my changes?

**Comment by PierrickVoulet** [comment]
> @PierrickVoulet, thank you!
> 
> I'm sorry, do i need commit with correct author(name, email) using a force push for the googlebot to approve my changes?

The issue is that the user who committed the change and requested the pull is **VI** which seem to not be you (@Neverage ). The change is pretty small, do you mind creating a new pull request with your GitHub username setup so that the consent works fine?

**Comment by Neverage** [comment]
@PierrickVoulet, done

**Comment by PierrickVoulet** [comment]
> @PierrickVoulet, done

Perfect! We should be able to merge this PR soon, thank you again.

**Comment by PierrickVoulet** [comment]
@Neverage The app now uses the V6 of the API that comes with `^6.0.0`, do you have some time to edit and test this PR one last time so that we can merge?

**Comment by Neverage** [comment]
@PierrickVoulet, done, thank you!

**Comment by PierrickVoulet** [comment]
Thank you for the quick turnaround and contribution @Neverage !

**Pull request merged**
