### PR TITLE
Update Helper.php

### PR DESCRIPTION
**Pull request by devorel**
Can you add it ?

### CODE REVIEW

**Comment by PierrickVoulet** [comment]
Hi @devorel - Thank you for the suggestion and writing this implementation. Quick question to better understand your intent: do you need these helpers for the development of your own applications?

**Comment by devorel** [comment]
hi yes
I use with it , it's prevents errors

**Comment by PierrickVoulet** [comment]
Thanks for the clarification and feedback, @devorel . In fact, something similar was developed for the code example [GetInvoices](https://github.com/googleads/google-ads-php/blob/master/examples/Billing/GetInvoices.php#L206) so we will plan on adding those soon. We will you keep posted.

**Comment by PierrickVoulet** [comment]
I opened another PR #506 following your lead, I suggest we continue working on this improvement from there. Thanks a lot for the contribution!

**Pull request closed without merging**
