### PR TITLE
Add Global examples: getLanguages and getUserInterest by taxonomyType

### PR DESCRIPTION
**Pull request by dsilvapereira**
Add examples to retrieve languages constant and user interest by taxonomy type

### CODE REVIEW

**Comment by dsilvapereira** [comment]
I signed it!

**Comment by dsilvapereira** [comment]
I signed it!

**Comment by fiboknacky** [comment]
Anash, could you please make a call about the directory locations?

**Comment by fiboknacky** [comment]
As there are no updates on this for a while, let me close this for now.
Feel free to re-open if you wish to proceed further. Thanks.

**Pull request closed without merging**
